"""
Django settings for museum_api project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from decouple import config
import dj_database_url
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-your-secret-key-here')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = ["*.vercel.app"]
DATABASES = {
    'default': dj_database_url.parse(config('DATABASE_URL'))
}


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'modeltranslation',  # Must be before django.contrib.admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'django_filters',
    'artifacts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'museum_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'museum_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

''''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='mcn'),
        'USER': config('DB_USER', default='Cardan'),
        'PASSWORD': config('DB_PASSWORD', default='Fatimata05?'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
    }
}
''' 

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'fr'

LANGUAGES = [
    ('fr', 'Français'),
    ('en', 'English'),
    ('wo', 'Wolof'),
]

MODELTRANSLATION_LANGUAGES = ('fr', 'en', 'wo')
MODELTRANSLATION_DEFAULT_LANGUAGE = 'fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

CORS_ALLOW_ALL_ORIGINS = True  # For development only

# Modeltranslation settings
MODELTRANSLATION_TRANSLATION_FILES = (
    'artifacts.translation',
)
# Chemin vers ton logo dans les fichiers statiques
JAZZMIN_SETTINGS = {
    "site_title": "Musée National du Sénégal",
    "site_header": "Administration du Musée",
    "site_brand": "Musée National du Sénégal",
    "site_logo": "images/logo_mcn.png",  # à mettre dans static/images/
    "welcome_sign": "Bienvenue à l’espace d’administration",
    "copyright": "© Musée National du Sénégal 2025",

    "search_model": "artifacts.Artifact",  # modèle par défaut à chercher

    "user_avatar": None,  # tu peux mettre un chemin si tu as un avatar admin

    "topmenu_links": [
        {"name": "Accueil", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"model": "auth.User", "permissions": ["auth.view_user"]},
        {"app": "artifacts", "name": "Artefacts"},
        {"app": "collections", "name": "Collections"},
    ],

    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "artifacts": "fas fa-archway",
        "collections": "fas fa-layer-group",
        "artifacts.Artifact": "fas fa-archway",
        "collections.Collection": "fas fa-book",
    },

    "default_icon_parents": True,
    "default_icon_children": True,

    "related_modal_active": True,
    "show_sidebar": True,

    "changeform_format": "horizontal_tabs",  # ou "collapsible", "tabs"
    "changeform_format_overrides": {
        "auth.user": "vertical_tabs",
    },

    "custom_links": {
        "artifacts": [
            {
                "name": "Importer Artefacts",
                "url": "import-artifacts",
                "icon": "fas fa-upload",
                "permissions": ["artifacts.add_artifact"],
            }
        ]
    },

    # Dashboard — tu peux définir des panneaux personnalisés
    "dashboard_exclude_apps": ["auth", "sessions", "admin"],
    "dashboard_title": "Statistiques du Musée",
}

# Tweaks visuels (couleurs, mode sombre, etc.)
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": True,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-light",
    "accent": "gold",
    "sidebar_nav_small_text": False,
    "sidebar_hide": False,
    "sidebar_legacy_style": False,
    "sidebar_flat_style": False,
    "sidebar_nav_compact": False,
    "sidebar_nav_legacy_expand": False,
    "sidebar_nav_toggle": True,
    "theme": "flatly",  # (clair et élégant)
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-outline-secondary",
        "delete": "btn-danger",
        "save": "btn-success",
    }
}

